"""Source policy, as compiled from the authoritative registry.

``policy/sources.json`` is generated by ``tooling/scripts/local-collector-policy.ts``
from ``docs/sources/pipeline/candidates.yaml``, the rights records and the
platform's prohibited-source list, and checked in CI. The collector reads it;
nothing in the collector (or its model) writes it. Unknown tasks, disabled
tasks and a missing or malformed policy all fail closed.

A local kill switch (dashboard or ``df_collector kill <task>``) can only take
permission away. The server independently re-checks every submission.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

POLICY_PATH = Path(__file__).resolve().parents[1] / "policy" / "sources.json"


class PolicyRefused(RuntimeError):
    pass


@dataclass(frozen=True)
class TaskPolicy:
    task: str
    source: str
    rights: str
    stage: str
    rights_record: str
    input: dict
    allowed_hosts: tuple[str, ...]
    intake_path: str
    min_interval_s: float


@dataclass(frozen=True)
class Policy:
    registry_sha256: str
    tasks: dict[str, dict]
    prohibited_domains: tuple[str, ...]
    datasets: dict[str, dict] = field(default_factory=dict)
    sources: dict[str, dict] = field(default_factory=dict)

    def task(self, name: str, kill_switch: bool = False) -> TaskPolicy:
        entry = self.tasks.get(name)
        if entry is None:
            raise PolicyRefused(f"task {name!r} is not in the compiled source policy")
        if not entry.get("enabled"):
            raise PolicyRefused(f"task {name!r} is disabled: {'; '.join(entry.get('refused_because') or ['no reason recorded'])}")
        if entry.get("rights") not in ("GREEN", "AMBER"):
            raise PolicyRefused(f"task {name!r} source rights are {entry.get('rights')!r}")
        if kill_switch:
            raise PolicyRefused(f"task {name!r} is stopped by the local kill switch")
        return TaskPolicy(
            task=name,
            source=entry["source"],
            rights=entry["rights"],
            stage=entry["stage"],
            rights_record=entry["rights_record"],
            input=entry["input"],
            allowed_hosts=tuple(entry["allowed_hosts"]),
            intake_path=entry["intake_path"],
            min_interval_s=float(entry.get("min_interval_s", 2)),
        )


def load(path: Path = POLICY_PATH) -> Policy:
    try:
        raw = json.loads(path.read_text())
        tasks = {entry["task"]: entry for entry in raw["tasks"]}
        return Policy(registry_sha256=raw["registry_sha256"], tasks=tasks, prohibited_domains=tuple(raw["prohibited_domains"]), datasets=raw.get("datasets", {}), sources=raw.get("sources", {}))
    except (OSError, KeyError, TypeError, ValueError) as error:
        raise PolicyRefused(f"source policy {path} is missing or malformed: {error}") from error
