import type { Trade } from './types.js';

/** The trade each ENERGY STAR product category belongs to. An unlisted category is a parse error, never a guess. */
export const CATEGORY_TRADE: Readonly<Record<string, Trade>> = {
  'Central Air Conditioners and Air Source Heat Pumps': 'hvac',
  Furnaces: 'hvac',
  'Geothermal Heat Pumps': 'hvac',
  'Light Commercial HVAC': 'hvac',
  Boilers: 'hvac',
  'Commercial Boilers': 'hvac',
  'Room Air Conditioners': 'hvac',
  'Ventilating Fans': 'hvac',
  'Connected Thermostats': 'hvac',
  Dehumidifiers: 'appliance',
  'Room Air Cleaners and Purifiers': 'appliance',
  'Water Heaters - Non Solar Electric and Non Solar Gas': 'plumbing',
  'Water Heaters - Solar Electric and Solar Gas': 'plumbing',
  'Commercial Water Heaters': 'plumbing',
  'Water Coolers': 'plumbing',
  'Pool Pumps': 'plumbing',
  'Consumer Refrigeration Products': 'appliance',
  Dishwashers: 'appliance',
  'Clothes Dryers': 'appliance',
  'Clothes Washers': 'appliance',
  'Residential Electric Cooking Products': 'appliance',
  Downlights: 'electrical',
  'Ceiling Fans': 'electrical',
  'Electric Vehicle Supply Equipment': 'electrical',
  'Uninterruptible Power Supplies': 'electrical',
  'Smart Home Energy Management Systems': 'electrical',
  Displays: 'electronics',
  'Imaging Equipment': 'electronics',
  Computers: 'electronics',
  'Enterprise Servers': 'electronics',
  Telephony: 'electronics',
  Televisions: 'electronics',
  'Data Center Storage': 'electronics',
  'Large Network Equipment': 'electronics',
  'Commercial Refrigerators and Freezers': 'commercial-food',
  'Commercial Ice Machines': 'commercial-food',
  'Commercial Dishwashers': 'commercial-food',
  'Commercial Ovens': 'commercial-food',
  'Commercial Hot Food Holding Cabinets': 'commercial-food',
  'Commercial Steam Cookers': 'commercial-food',
  'Commercial Fryers': 'commercial-food',
  'Commercial Griddles': 'commercial-food',
  'Commercial Electric Cooktops': 'commercial-food',
  'Commercial Coffee Brewers': 'commercial-food',
  'Vending Machines': 'commercial-food',
  'Storm Windows': 'building-envelope',
  'Lab Grade Refrigerators and Freezers': 'lab',
};
