/** Compile filesystem-free artifact-processing configuration. Unsupported formats are explicit. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { compileSourcePlans, type SourcePlan } from '../../services/ingest-worker/src/compile.js';
import type { AcquisitionRuntimeTarget } from '../../packages/acquisition/src/runtime.js';
import { loadVerticalConfig } from '../../services/ingest-worker/src/config.js';
import { INGESTION_LIMITS, ingestionRuntimeDigest, type IngestionRuntime } from '../../services/ingest-worker/src/runtime.js';
import { compileAcquisitionRuntime, REPO_ROOT } from './compile-acquisition-runtime.js';
import { readIngestionImplementation } from '../lib/ingestion-implementation.js';
import { isMain } from '../lib/cli-entry.js';
export const OUTPUT_DIR = join(REPO_ROOT, 'apps/ingestion-worker/generated');
/** Reviewed processing composition; acquisition bundle presence is not admission. */
export const BUNDLED_INGESTION_VERTICALS = ['hvac'] as const;
export function qualifyIngestionSources(plans: readonly SourcePlan[], targets: readonly AcquisitionRuntimeTarget[]): Pick<IngestionRuntime, 'supported_source_keys' | 'source_targets' | 'unsupported_sources'> {
  const supported: string[] = [];
  const sourceTargets: { source_key: string; target_id: string }[] = [];
  const unsupported: Array<IngestionRuntime['unsupported_sources'][number]> = [];
  for (const plan of plans) {
    const formats = [...new Set(plan.streams.map(stream => stream.schema.format))].sort();
    const sourceTarget = targets.filter(target => target.source.key === plan.sourceKey);
    if (formats.some(format => format !== 'json' && format !== 'csv')) {
      unsupported.push({ source_key: plan.sourceKey, formats, reason: 'UNSUPPORTED_FORMAT' });
    } else if (sourceTarget.length !== 1) {
      unsupported.push({ source_key: plan.sourceKey, formats, reason: 'SOURCE_TARGET_PARTITION_REQUIRED' });
    } else {
      supported.push(plan.sourceKey);
      sourceTargets.push({ source_key: plan.sourceKey, target_id: sourceTarget[0]!.target_id });
    }
  }
  return { supported_source_keys: supported.sort(), source_targets: sourceTargets.sort((a,b) => a.source_key.localeCompare(b.source_key)), unsupported_sources: unsupported };
}
export async function compileIngestionRuntime(slug: string): Promise<IngestionRuntime> {
  const config = await loadVerticalConfig(slug);
  const { registry: _registry, directory: _directory, ...serialized } = config;
  const plans = compileSourcePlans(config);
  const acquisition = await compileAcquisitionRuntime(slug);
  const payload: Omit<IngestionRuntime, 'runtime_digest'> = {
    version: 1, vertical_slug: slug,
    ...await readIngestionImplementation(REPO_ROOT),
    acquisition_runtime_digest: acquisition.runtime_digest,
    ...qualifyIngestionSources(plans, acquisition.targets),
    limits: INGESTION_LIMITS, config: serialized,
  };
  return { ...payload, runtime_digest: ingestionRuntimeDigest(payload) };
}
export async function run(slugs: readonly string[], check = false, outputDir = OUTPUT_DIR): Promise<number> {
  const artifacts = new Map<string, string>();
  for (const slug of slugs) artifacts.set(`${slug}.ingestion-runtime.json`, `${JSON.stringify(await compileIngestionRuntime(slug), null, 2)}\n`);
  artifacts.set('runtime-registry.ts', [
    '/** Generated by tooling/scripts/compile-ingestion-runtime.ts. Do not edit. */',
    "import type { IngestionRuntime } from '../../../services/ingest-worker/src/runtime.js';",
    ...slugs.map((slug, i) => `import runtime${i} from './${slug}.ingestion-runtime.json' with { type: 'json' };`),
    'export const INGESTION_RUNTIMES: Readonly<Record<string, IngestionRuntime>> = {',
    ...slugs.map((slug, i) => `  ${JSON.stringify(slug)}: runtime${i} as IngestionRuntime,`),
    '};', '',
  ].join('\n'));
  await mkdir(outputDir, { recursive: true });
  for (const [name, content] of artifacts) {
    const file = join(outputDir, name);
    if (check) { if (await readFile(file, 'utf8').catch(() => '') !== content) return 1; }
    else await writeFile(file, content, 'utf8');
  }
  return 0;
}
if (isMain(import.meta.url)) run(BUNDLED_INGESTION_VERTICALS, process.argv.includes('--check')).then(code => { process.exitCode = code; });
