/**
 * Two things must never leave in an export: who reviewed something, and what we
 * wrote down internally about a source.
 *
 * REVIEWER IDENTITY. `@data-foundry/query-model` states the guarantee — "the
 * REVIEWER IDENTITY is never projected onto any of these shapes" — and ships
 * `assertNoReviewerIdentity` as the control. This module applies that control at
 * the export boundary, and widens the reviewer set while doing it.
 *
 * The widening is the point. `canonicalFacts` checks a correction's reason
 * against the reviewer of THAT correction, which is the only reviewer it has in
 * hand at that moment. An export knows the whole compiled policy, so it checks
 * every reason against EVERY reviewer the policy declares. A reason reading
 * "corrected by j.okafor after a supplier call", attached to an override whose
 * declared reviewer is m.chen, passes the query layer and is caught here. It is
 * the same control with a bigger haystack, not a second implementation:
 * `assertNoReviewerIdentity` is imported rather than reimplemented, so the two
 * agree about what an identity looks like by construction.
 *
 * TWO STRENGTHS, ON PURPOSE. The query-model control matches derived tokens —
 * `legal@example.com` also matches a bare `legal`. That net is right for a
 * human-authored sentence and wrong for machine-generated bytes, where a
 * manifest field literally named `requires_legal_review` would trip it and
 * refuse a perfectly clean export. So authored prose (correction reasons) gets
 * the derived-token net, and the whole-artifact sweep matches the full declared
 * identity only. Both refuse; neither guesses.
 *
 * INTERNAL NOTES. A `SourceRegistryEntry` carries text that exists for us and
 * not for a customer: `notes`, `geographic_notes`, the acquisition approver, the
 * licence-text file path, the rights reviewer. The manifest builder copies
 * fields onto an allow-list basis rather than spreading the entry, so none of it
 * travels — and `assertNoInternalText` checks the SERIALIZED BYTES rather than
 * the object, because a field-by-field check is only ever as good as the list of
 * fields somebody remembered to write down.
 */
import {
  ReviewerIdentityLeak,
  assertNoReviewerIdentity,
  correctionFields,
  type CanonicalFactView,
} from '@data-foundry/query-model';
import type { SourceRegistryEntry } from '@data-foundry/source-registry';
import type { EditorialOverride } from '@data-foundry/canonical-store';
import { InternalTextLeak } from './errors.js';

/**
 * Every human named anywhere in the inputs to this export.
 *
 * Deliberately generous: an approver is as much a staff identity as a reviewer,
 * and a manifest is not the place for either.
 */
export function declaredReviewers(
  overrides: readonly EditorialOverride[],
  registry: readonly SourceRegistryEntry[],
): readonly string[] {
  const names = new Set<string>();
  for (const override of overrides) {
    if (typeof override.reviewer === 'string' && override.reviewer.trim() !== '') {
      names.add(override.reviewer.trim());
    }
  }
  for (const entry of registry) {
    for (const name of [entry.rights_policy.reviewed_by, entry.acquisition_policy.approved_by]) {
      if (name !== null && name.trim() !== '') names.add(name.trim());
    }
  }
  return [...names];
}

/**
 * The query-layer control, applied to each row about to be published, against
 * the full reviewer set rather than one correction's own reviewer.
 */
export function assertRowsCarryNoReviewerIdentity(
  views: readonly CanonicalFactView[],
  reviewers: readonly string[],
): void {
  if (reviewers.length === 0) return;
  for (const view of views) {
    assertNoReviewerIdentity(correctionFields(view), reviewers);
  }
}

/**
 * Sweep a serialized artifact for a full declared identity.
 *
 * Checking the bytes rather than the object is the whole point: the failure
 * mode being guarded against is a field nobody thought to check.
 */
export function assertArtifactCarriesNoReviewerIdentity(
  path: string,
  serialized: string,
  reviewers: readonly string[],
): void {
  const haystack = serialized.toLowerCase();
  for (const reviewer of reviewers) {
    const needle = reviewer.trim().toLowerCase();
    if (needle !== '' && haystack.includes(needle)) throw new ReviewerIdentityLeak(path);
  }
}

/**
 * Text from a source declaration that is written for us, not for a customer.
 *
 * Short fragments are skipped: a four-character note is a substring of
 * everything and would refuse every export, which is the same reason
 * `reviewerIdentityTokens` declines to derive short tokens.
 */
const MIN_INTERNAL_FRAGMENT = 12;

export function internalOnlyText(registry: readonly SourceRegistryEntry[]): readonly string[] {
  const fragments = new Set<string>();
  for (const entry of registry) {
    for (const text of [
      entry.notes,
      entry.rights_policy.geographic_notes,
      entry.rights_policy.license_text_ref,
      entry.acquisition_policy.notes,
      entry.license_split.notes,
    ]) {
      if (typeof text === 'string' && text.trim().length >= MIN_INTERNAL_FRAGMENT) {
        fragments.add(text.trim());
      }
    }
  }
  return [...fragments];
}

export function assertNoInternalText(
  path: string,
  serialized: string,
  fragments: readonly string[],
): void {
  const haystack = serialized.toLowerCase();
  for (const fragment of fragments) {
    if (haystack.includes(fragment.toLowerCase())) throw new InternalTextLeak(path);
  }
}
