/**
 * Tool input schemas — one definition, used both to validate and to publish.
 *
 * The classic MCP defect is a declared `inputSchema` that nothing enforces: the
 * schema says `limit` is at most 50, the handler happily runs with 5000, and
 * the mismatch is invisible until a caller trusts the declaration. That is
 * avoided here by construction rather than by review — the published JSON
 * Schema is `z.toJSONSchema()` of the very Zod schema the dispatcher parses
 * with, generated by the same call `tooling/scripts/generate-json-schemas.ts`
 * makes for the canonical objects. There is no second artefact to keep in step.
 *
 * `io: 'input'` matters: a tool's declared schema describes what a CALLER may
 * send, so defaults appear as `default` and defaulted fields are not `required`.
 *
 * Every object is strict. An unrecognised argument is an error, not a silently
 * dropped key — a caller that misspells `entity_id` should be told, not served
 * a different question's answer.
 */
import { z } from 'zod';
import {
  EntityIdArg,
  FreeTextIdentifierArg,
  IdentifierArg,
  TimestampArg,
} from './canonical-schemas.js';

/** Facet filters, mirroring the query layer's `FacetFilter` union exactly. */
const FilterArg = z.discriminatedUnion('op', [
  z.strictObject({
    property: IdentifierArg.describe('Declared, filterable field for this vertical.'),
    op: z.literal('in'),
    values: z
      .array(z.union([z.string(), z.number(), z.boolean()]))
      .min(1)
      .describe('Match any of these values.'),
  }),
  z.strictObject({
    property: IdentifierArg,
    op: z.literal('range'),
    min: z.number().nullable().default(null),
    max: z.number().nullable().default(null),
  }),
  z.strictObject({
    property: IdentifierArg,
    op: z.literal('exists'),
  }),
]);

export const SearchEntitiesInput = z
  .strictObject({
    query: FreeTextIdentifierArg.optional().describe(
      'Free text, or an exact identifier in any formatting. An exact identifier match is ' +
        'returned ahead of every ranked text match, never blended into a score.',
    ),
    entity_type: IdentifierArg.optional().describe(
      'Restrict to one vertical-declared entity type, e.g. "equipment".',
    ),
    filters: z
      .array(FilterArg)
      .max(10)
      .optional()
      .describe(
        'Field filters. A field the vertical does not declare as filterable is rejected ' +
          'rather than ignored.',
      ),
    include_retired: z
      .boolean()
      .default(false)
      .describe('Also return entities retired from the catalogue.'),
    include_facets: z.boolean().default(false).describe('Return facet counts alongside the hits.'),
    limit: z.number().int().min(1).max(50).default(20),
    offset: z.number().int().min(0).max(10_000).default(0),
  })
  .describe('Arguments for search_entities.');

export const GetEntityInput = z
  .strictObject({
    identifier: FreeTextIdentifierArg.describe(
      'A canonical entity id, a canonical slug, or any recorded identifier/alias in any ' +
        'formatting.',
    ),
    entity_type: IdentifierArg.optional().describe(
      'Disambiguates identifiers that are only unique within a type, and is required to ' +
        'resolve a bare slug.',
    ),
    include_facts: z
      .boolean()
      .default(true)
      .describe('Include the canonical fact sheet. Set false for identity resolution only.'),
  })
  .describe('Arguments for get_entity.');

export const ListFactsInput = z
  .strictObject({
    entity_id: EntityIdArg.describe('Canonical entity id, as returned by get_entity or search.'),
    properties: z
      .array(IdentifierArg)
      .min(1)
      .max(50)
      .optional()
      .describe('Restrict to these properties. Omit for the whole fact sheet.'),
    as_of: TimestampArg.optional().describe(
      'Read the fact sheet as it stood at this instant. Defaults to now.',
    ),
  })
  .describe('Arguments for list_facts.');

export const CompareEntitiesInput = z
  .strictObject({
    entity_ids: z
      .array(EntityIdArg)
      .min(2)
      .max(5)
      .describe('Canonical entity ids. Resolve identifiers with get_entity first.'),
    properties: z
      .array(IdentifierArg)
      .min(1)
      .max(50)
      .optional()
      .describe('Restrict the comparison. Defaults to every property any of them holds.'),
  })
  .describe('Arguments for compare_entities.');

export const TraverseRelationshipsInput = z
  .strictObject({
    entity_id: EntityIdArg,
    predicate: IdentifierArg.optional().describe(
      'Restrict to one vertical-declared predicate, e.g. "replaced_by".',
    ),
    direction: z.enum(['out', 'in', 'both']).default('both'),
    depth: z.number().int().min(1).max(4).default(1).describe('Hops to follow. Capped at 4.'),
    limit: z.number().int().min(1).max(200).default(50),
  })
  .describe('Arguments for traverse_relationships.');

export const ExplainFactInput = z
  .strictObject({
    entity_id: EntityIdArg,
    property: IdentifierArg.describe('The single property to explain.'),
    as_of: TimestampArg.optional().describe('Explain the selection as it stood at this instant.'),
  })
  .describe('Arguments for explain_fact.');

/** A JSON Schema document, as published in a tool definition. */
export type JsonSchemaDocument = Readonly<Record<string, unknown>>;

/**
 * The published schema for a tool, generated from its validator.
 *
 * Same generator call as `tooling/scripts/generate-json-schemas.ts` uses for
 * the canonical objects, so a tool definition and a canonical object export
 * describe a string the same way.
 */
export function publishInputSchema(schema: z.ZodType): JsonSchemaDocument {
  return z.toJSONSchema(schema, { target: 'draft-2020-12', io: 'input' }) as JsonSchemaDocument;
}
